#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port2,           strafe,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int l = 0;
int r = 0;
int s = 0;

task main(){
	while (1 == 1) {
		l = 0;
		r = 0;
		s = 0;

		if (abs(vexRT[Ch3]) > 20) {
			l += vexRT[Ch3];
			r += vexRT[Ch3];
		}
		if (abs(vexRT[Ch1]) > 20) {
			l += vexRT[Ch1];
			r -= vexRT[Ch1];
			s -= vexRT[Ch1];
		}
		if (abs(vexRT[Ch4]) > 20) {
			s += vexRT[Ch4];
		}

		motor[left] = -l;
		motor[right] = -r;
		motor[strafe] = s;
	}
}
